name: Increment value test
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Increment value test
    runs-on: ubuntu-latest
    steps:
      - name: Increment value
        uses: yoichiro/gh-action-increment-value@main
        with:
          target-file: 'build-number.json'
          prefix: '{"buildNumber":'
          suffix: '}'

