name: Deploy for Production
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/build-number.json'
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          repository: yoichiro/gh-action-increment-value-test
          ref: main
          token: ${{ secrets.INCREMENT_VALUE_PAT }}
      - name: Increment value
        uses: yoichiro/gh-action-increment-value@main
        with:
          target_directory: 'foobar/baz'
          target_file: 'build-number.json'
          prefix: '{"buildNumber":'
          suffix: '}'
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: yarn build
