name: Deploy for Production
on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Increment value
        uses: yoichiro/gh-action-increment-value@main
        with:
          target_directory: 'foobar/baz'
          target_file: 'build-number.json'
          prefix: '{"buildNumber":'
          suffix: '}'
        env:
          GITHUB_TOKEN: ${{ secrets.INCREMENT_VALUE_PAT }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install dependencies
        run: npm install
      - name: Build
        run: yarn build
